### ISSUE TITLE
When will the source code be fully open to the public?

### ISSUE THREAD

**Issue by panxingyu666** [nightkeepers/CI-SSOD#1]
This is a very great job, and I am very interested in it. Would you be willing to share the method code publicly? Thank you very much.

**Comment by lijm48** [comment]
We will complete the training procedure within a month. Actually, you can find the method code mainly at https://github.com/nightkeepers/CI-SSOD/blob/main/ssod/models/soft_teacher_grs.py and https://github.com/nightkeepers/CI-SSOD/blob/main/ssod/models/losses/gbr_optim.py.
